### ISSUE TITLE
Integrate OpencloudMesh dev environment into new structure.

### ISSUE THREAD

**Issue by MahdiBaghbani** [pondersource/dev-stock#28]

**Comment by michielbdejong** [comment]
Here, "OpencloudMesh dev environment" refers to the current practice of the surf-rd-sram team of:
* checking out https://github.com/pondersource/dev-stock/tree/oc-opencloudmesh-testing instead of https://github.com/pondersource/dev-stock/tree/main
* building Docker images instead of pulling them from Docker hub -> see #29

Right?
