### ISSUE TITLE
Logging broken in latest pondersource/dev-stock-nc1-sciencemesh-network-beta?

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/dev-stock#35]
To reproduce:
```
ssh root@cloud.pondersource.org
cd ocm-test-suite
./scripts/clean.sh
docker pull pondersource/dev-stock-nc1-sciencemesh-network-beta
./scripts/start-public-Nextcloud.sh
docker logs -f nc1.docker
```
In another window:
```
curl -i https://cloud.pondersource.org/index.php/apps/sciencemesh/api/v1/some-wrong-path
```

You'll see no error appear in the docker logs

**Comment by MahdiBaghbani** [comment]
I don't think that is the latest, 
https://hub.docker.com/r/pondersource/dev-stock-nc1-sciencemesh-network-beta
it has always been this since a month ago. new dev-stock does not build `dev-stock-nc1-sciencemesh-network-beta` it only builds `dev-stock-nextcloud-sciencemesh`

then it tags the image as multiple other images in init script:
https://github.com/pondersource/dev-stock/blob/4391b50ce2ae3b3cc4f0c7197b3ff3f0624cd969/scripts/init-sciencemesh.sh#L29-L33

**Comment by michielbdejong** [comment]
I'll test again with the latest image
